### ISSUE TITLE
Restore password

### ISSUE THREAD

**Issue by ArcoMul** [ArcoMul/leihbase#24]
Add 'Forgot password?' to login form, and connect to provided Pocketbase functionality.

**Comment by maxverlaufen** [comment]
Also add "Change password" in https://katalog.leihbar-koeln.org/profile 
If it's the same Pocketbase functionality? Or should this be its own issue?

**Comment by ArcoMul** [comment]
Closed by https://github.com/ArcoMul/leihbase/commit/98e560177c49d5e42fc2f4e8638547be60d4e534
