### ISSUE TITLE
Admin Interface, new reservation, add emoticon button in editor

### ISSUE THREAD

**Issue by maxverlaufen** [ArcoMul/leihbase#29]
A user without access to pocketbase would probably like to add the icons to the Notiz-category as well. Can a button for emoticons be added to the editor? Or can it maybe be prefilled with the checkmark and the money icon?

**Comment by ArcoMul** [comment]
The emojis can be added using the emoji keyboard of the mobile phone, or using emoji input on [Mac and Windows](https://support.airship.com/hc/en-us/articles/360039248612-Using-Emoji-from-your-Windows-or-Mac-computer). Did you try that? Would that be sufficient? An emoji button/selector would be nice, but is not so straight forward to add.

**Comment by maxverlaufen** [comment]
Sounds good. Let's add it to the instructions and it should be sufficient.
