### ISSUE TITLE
Reservation start and end e-mail reminders

### ISSUE THREAD

**Issue by ArcoMul** [ArcoMul/leihbase#41]
- Send users an e-mail reminder that their reservation is starting, and their product can be picked up one day before reservation start
- Send users an e-mail reminder to bring back their product one day before reservation end

## Templates

Reservation start reminder:

>Hallo, 
>
>du hast bei {location-name} den Gegenstand {product-name} reserviert. Der Gegenstand liegt morgen ({datum}) zwischen {start-hour} und {end-hour} bereit. Bitte denke daran, deinen Gegenstand abzuholen. Falls du ihn nicht mehr benötigst, antworte auf diese Mail, um deine Reservierung zu stornieren.
>
>Danke, dass du dich für Leihen statt Kaufen entscheidest!
>
>Liebe Grüße
>Dein LeihBar-Team

Reservation end reminder:

>Hallo,
>
>wir hoffen, mit dem Gegenstand {product-name} hat alles gut funktioniert!
>
>Deine Leihfrist endet morgen, also bring uns den Gegenstand bitte zurück zur {location-name}.
>
>{location-name} ist geöffnet von {open-start} bis {open-end}.
>
>Danke, und bis morgen!
>
>Liebe Grüße
>dein LeihBar-Team

---

## Progress

- [ ] Add 'start_reminder' and 'end_reminder' boolean field to reservation
- [ ] Add cron hook to run every hour
- [ ] In cron hook fetch all reservations starting tomorrow, if the current time is less than 24 hours of the next opening hours
- [ ] For every reservation send an e-mai reminder and mark that the reminder has been sent

**Comment by ArcoMul** [comment]
https://pocketbase.io/docs/js-jobs-scheduling/

**Comment by ArcoMul** [comment]
Reservation start reminder:

>Hallo, 
>
>du hast bei {location-name} den Gegenstand {product-name} reserviert. Der Gegenstand liegt morgen ({datum}) zwischen {start-hour} und {end-hour} bereit. Bitte denke daran, deinen Gegenstand abzuholen. Falls du ihn nicht mehr benötigst, antworte auf diese Mail, um deine Reservierung zu stornieren.
>
>Danke, dass du für Leihen statt kaufen wählst!
>
>Liebe Grüße
>Dein LeihBar-Team

**Comment by maxverlaufen** [comment]
Just one small thing:
> > Danke, dass du dich für Leihen statt Kaufen entscheidest!

**Comment by ArcoMul** [comment]
Reservation end reminder:

>Hallo,
>
>Wir hoffen, es hat gut geklappt mit den Gegenstand {product-name}!
>
>Morgen erwarten wir es wieder zurück am {location-name}, bringst du es wieder zurück?
>
>{location-name} ist geöffnet von {open-start} bis {open-end}.
>
>Danke, und bis morgen!
>
>Liebe Grüße
>dein LeihBar-Team

**Comment by maxverlaufen** [comment]
> Reservation end reminder:
> 
> > Hallo,
> > wir hoffen, mit dem Gegenstand {product-name} hat alles gut funktioniert!
> > Deine Leihfrist endet morgen, also bring uns den Gegenstand bitte zurück zur {location-name}.
> > {location-name} ist geöffnet von {open-start} bis {open-end}.
> > Danke, und bis morgen!
> > Liebe Grüße
> > dein LeihBar-Team

Changed to statement instead of question, so user doesn't feel the need to answer (as it is just a reminder).

**Comment by ArcoMul** [comment]
@maxverlaufen What do you think of these email subjects? Are they spelled correctly?

> Reservierung start: "Abholen des Gegenstands '{productName}'"

> Reservierung ende: "Zurückbringen des Gegenstands '{productName}'"

**Comment by maxverlaufen** [comment]
> @maxverlaufen What do you think of these email subjects? Are they spelled correctly?
> 
> > Reservierung start: "Abholen des Gegenstands '{productName}'"
> 
> > Reservierung ende: "Zurückbringen des Gegenstands '{productName}'"

Yep, perfect!
